accent = "#66B3FF"
cursor = "#F2F7FF"
foreground = "#EDF4FF"
background = "#090C10"

selection_foreground = "#F2F7FF"
selection_background = "#66B3FF"

color0  = "#151A22"
color1  = "#FF7D8D"
color2  = "#97D88A"
color3  = "#F2D48B"
color4  = "#66B3FF"
color5  = "#9DB8FF"
color6  = "#7EEFFF"
color7  = "#D6E2F5"

color8  = "#202734"
color9  = "#FF9CAB"
color10 = "#B4E9A6"
color11 = "#FFE5A6"
color12 = "#8AC9FF"
color13 = "#B8C8FF"
color14 = "#A1F4FF"
color15 = "#F8FAFF"
