$activeBorderColor = rgb(66B3FF)
$inactiveBorderColor = rgb(202734)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
}
