background = #090C10
foreground = #EDF4FF
cursor-color = #F2F7FF

selection-background = #66B3FF
selection-foreground = #F2F7FF

palette = 0=#151A22
palette = 1=#FF7D8D
palette = 2=#97D88A
palette = 3=#F2D48B
palette = 4=#66B3FF
palette = 5=#9DB8FF
palette = 6=#7EEFFF
palette = 7=#D6E2F5

palette = 8=#202734
palette = 9=#FF9CAB
palette = 10=#B4E9A6
palette = 11=#FFE5A6
palette = 12=#8AC9FF
palette = 13=#B8C8FF
palette = 14=#A1F4FF
palette = 15=#F8FAFF

font-family = JetBrainsMono Nerd font-family
font-size = 13
